export const COMMON_API_ERROR_CODES = {
  CONFLICT: "COMMON_CONFLICT",
  DOMAIN_VALIDATION_FAILED: "COMMON_DOMAIN_VALIDATION_FAILED",
  UNAUTHORIZED: "COMMON_UNAUTHORIZED",
  RATE_LIMITED: "COMMON_RATE_LIMITED",
  VALIDATION_FAILED: "COMMON_VALIDATION_FAILED",
} as const;

export type CommonApiErrorCode =
  (typeof COMMON_API_ERROR_CODES)[keyof typeof COMMON_API_ERROR_CODES];

export const AUTH_API_ERROR_CODES = {
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
  ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
  INVALID_REFRESH_TOKEN: "AUTH_INVALID_REFRESH_TOKEN",
  VERIFICATION_FAILED: "AUTH_VERIFICATION_FAILED",
  INVALID_RESET_TOKEN: "AUTH_INVALID_RESET_TOKEN",
} as const;

export type AuthApiErrorCode =
  (typeof AUTH_API_ERROR_CODES)[keyof typeof AUTH_API_ERROR_CODES];

export const USER_API_ERROR_CODES = {
  EMAIL_ALREADY_EXISTS: "USER_EMAIL_ALREADY_EXISTS",
  NOT_FOUND: "USER_NOT_FOUND",
} as const;

export type UserApiErrorCode =
  (typeof USER_API_ERROR_CODES)[keyof typeof USER_API_ERROR_CODES];

export const CLIENT_API_ERROR_CODES = {
  NOT_FOUND: "CLIENT_NOT_FOUND",
  CPF_ALREADY_REGISTERED: "CLIENT_CPF_ALREADY_REGISTERED",
  CNPJ_ALREADY_REGISTERED: "CLIENT_CNPJ_ALREADY_REGISTERED",
  DUPLICATE_DOCUMENT: "CLIENT_DUPLICATE_DOCUMENT",
  INVALID_DATA: "CLIENT_INVALID_DATA",
} as const;

export type ClientApiErrorCode =
  (typeof CLIENT_API_ERROR_CODES)[keyof typeof CLIENT_API_ERROR_CODES];

export const TICKET_API_ERROR_CODES = {
  NOT_FOUND: "TICKET_NOT_FOUND",
  ACCESS_DENIED: "TICKET_ACCESS_DENIED",
  INVALID_VERSION: "TICKET_INVALID_VERSION",
  USER_NOT_FOUND: "TICKET_USER_NOT_FOUND",
} as const;

export type TicketApiErrorCode =
  (typeof TICKET_API_ERROR_CODES)[keyof typeof TICKET_API_ERROR_CODES];

export const CONTRACT_API_ERROR_CODES = {
  NOT_FOUND: "CONTRACT_NOT_FOUND",
  CLIENT_NOT_FOUND: "CONTRACT_CLIENT_NOT_FOUND",
  INVALID_DATA: "CONTRACT_INVALID_DATA",
} as const;

export type ContractApiErrorCode =
  (typeof CONTRACT_API_ERROR_CODES)[keyof typeof CONTRACT_API_ERROR_CODES];

export const LOCATION_API_ERROR_CODES = {
  COUNTRY_NOT_FOUND: "LOCATION_COUNTRY_NOT_FOUND",
  COUNTRY_REFERENCED: "LOCATION_COUNTRY_REFERENCED",
  PARENT_COUNTRY_INVALID: "LOCATION_PARENT_COUNTRY_INVALID",
  STATE_NOT_FOUND: "LOCATION_STATE_NOT_FOUND",
  STATE_REFERENCED: "LOCATION_STATE_REFERENCED",
  PARENT_STATE_INVALID: "LOCATION_PARENT_STATE_INVALID",
  CITY_NOT_FOUND: "LOCATION_CITY_NOT_FOUND",
  CITY_REFERENCED: "LOCATION_CITY_REFERENCED",
  GEO_CITY_NOT_FOUND: "LOCATION_GEO_CITY_NOT_FOUND",
  GEO_CITY_STATE_MISMATCH: "LOCATION_GEO_CITY_STATE_MISMATCH",
  GEO_STATE_CODE_REQUIRED: "LOCATION_GEO_STATE_CODE_REQUIRED",
} as const;

export type LocationApiErrorCode =
  (typeof LOCATION_API_ERROR_CODES)[keyof typeof LOCATION_API_ERROR_CODES];

export const CLIENT_UI_ERROR_CODES = {
  REQUEST_FAILED: "CLIENT_REQUEST_FAILED",
  INVALID_ACCESS_TOKEN: "CLIENT_INVALID_ACCESS_TOKEN",
} as const;

export type ClientUiErrorCode =
  (typeof CLIENT_UI_ERROR_CODES)[keyof typeof CLIENT_UI_ERROR_CODES];

const REGISTERED_API_ERROR_CODE_VALUES: ReadonlySet<string> = new Set([
  ...Object.values(COMMON_API_ERROR_CODES),
  ...Object.values(AUTH_API_ERROR_CODES),
  ...Object.values(USER_API_ERROR_CODES),
  ...Object.values(CLIENT_API_ERROR_CODES),
  ...Object.values(TICKET_API_ERROR_CODES),
  ...Object.values(CONTRACT_API_ERROR_CODES),
  ...Object.values(LOCATION_API_ERROR_CODES),
  ...Object.values(CLIENT_UI_ERROR_CODES),
]);

export function isRegisteredLocalizedApiErrorCode(code: string): boolean {
  return REGISTERED_API_ERROR_CODE_VALUES.has(code);
}

export type AnyApiErrorCode =
  | CommonApiErrorCode
  | AuthApiErrorCode
  | UserApiErrorCode
  | ClientApiErrorCode
  | TicketApiErrorCode
  | ContractApiErrorCode
  | LocationApiErrorCode
  | ClientUiErrorCode;
