export const AUTH_API_ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  VERIFICATION_FAILED: 'AUTH_VERIFICATION_FAILED',
  INVALID_RESET_TOKEN: 'AUTH_INVALID_RESET_TOKEN',
} as const;

export type AuthApiErrorCode = (typeof AUTH_API_ERROR_CODES)[keyof typeof AUTH_API_ERROR_CODES];
